let mockRestuarantSearch = [
  {
    name: "El Toro Loco",
    rating: 4.2,
    ratingCount: 1587,
    cuisine: "Mexican",
    priceRange: 2,
    location: "Cambrian Park",
    closingTime: "3 AM",
    openingTime: "9 AM",
    isClosed: true,
  },
  {
    name: "Taqueria Azteca",
    rating: 3.8,
    ratingCount: 932,
    cuisine: "Mexican",
    priceRange: 1,
    location: "Cambrian Park",
    closingTime: "3 AM",
    openingTime: "9 AM",
    isClosed: true,
  },
  {
    name: "Casa de Sabor",
    rating: 4.5,
    ratingCount: 2103,
    cuisine: "Mexican",
    priceRange: 3,
    location: "Cambrian Park",
    closingTime: "3 AM",
    openingTime: "9 AM",
    isClosed: false,
  },
  {
    name: "Burrito Bandidos",
    rating: 3.9,
    ratingCount: 756,
    cuisine: "Mexican",
    priceRange: 1,
    location: "Cambrian Park",
    closingTime: "3 AM",
    openingTime: "9 AM",
    isClosed: false,
  },
  {
    name: "Fiesta Mexicana",
    rating: 4.1,
    ratingCount: 1345,
    cuisine: "Mexican",
    priceRange: 2,
    location: "Cambrian Park",
    closingTime: "3 AM",
    openingTime: "9 AM",
    isClosed: false,
  },
  {
    name: "Cantina del Sol",
    rating: 4.7,
    ratingCount: 1876,
    cuisine: "Mexican",
    priceRange: 3,
    location: "Cambrian Park",
    closingTime: "3 AM",
    openingTime: "9 AM",
    isClosed: false,
  },
  {
    name: "Taco Loco",
    rating: 3.5,
    ratingCount: 543,
    cuisine: "Mexican",
    priceRange: 1,
    location: "Cambrian Park",
    closingTime: "3 AM",
    openingTime: "9 AM",
    isClosed: false,
  },
  {
    name: "El Mariachi Grill",
    rating: 4.3,
    ratingCount: 1678,
    cuisine: "Mexican",
    priceRange: 2,
    location: "Cambrian Park",
    closingTime: "3 AM",
    openingTime: "9 AM",
    isClosed: false,
  },
  {
    name: "Sabor a Mexico",
    rating: 4.0,
    ratingCount: 987,
    cuisine: "Mexican",
    priceRange: 2,
    location: "Cambrian Park",
    closingTime: "3 AM",
    openingTime: "9 AM",
    isClosed: false,
  },
  {
    name: "La Hacienda",
    rating: 4.6,
    ratingCount: 2234,
    cuisine: "Mexican",
    priceRange: 3,
    location: "Cambrian Park",
    closingTime: "3 AM",
    openingTime: "9 AM",
    isClosed: false,
  },
];
export default mockRestuarantSearch;
